# Generated by Django 5.0.7 on 2024-09-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="account",
            new_name="account_name",
        ),
    ]
