# Generated by Django 5.0.7 on 2024-09-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recurringtransaction",
            old_name="transaction",
            new_name="transaction_type",
        ),
    ]
