# Generated by Django 5.0.7 on 2024-09-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_transaction_recurringtransaction_transaction_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="account_name",
            new_name="account",
        ),
    ]
